### ISSUE TITLE
Update Gulp File & delete grunt file

### ISSUE THREAD

**Issue by stridentbean** [inverted-murmuration/project#5]
Include what?

watch -> devbuild

devbuild
jshint, test, ionic serve --lab

prodbuild
min / concat, jshint, test, deploy

**Comment by JAFong** [comment]
Gulp configured to test with Karma. Look into Angular Mocks when creating tests.

**Comment by JAFong** [comment]
Gulp configured to run on all javascript files in www/js folder.

**Comment by JAFong** [comment]
Commands added:
gulp test: runs jsLint; need to set up Karma testing with mocha and chai
gulp build: concats then uglifys all files within www/js folder
gulp dev: currently only calls test
gulp prod: runs build, test then deploy
gulp deploy: runs "ionic upload" in cli
gulp watch: watches all SASS files and compiles to CSS
watches all JS files and runs test
